// Generated by tools/gen_kernel_stubs.py -- do not edit.
// Every import here logs once and returns 0, so a run reports exactly
// which ones the game actually reaches.
#include <ppc_recomp_shared.h>
#include "kernel/kernel.h"

PPC_FUNC(__imp__KeBugCheck) { kernel::Unimplemented("KeBugCheck"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__KeBugCheckEx) { kernel::Unimplemented("KeBugCheckEx"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__NtQueryDirectoryFile) { kernel::Unimplemented("NtQueryDirectoryFile"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__RtlImageXexHeaderField) { kernel::Unimplemented("RtlImageXexHeaderField"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__RtlRaiseException) { kernel::Unimplemented("RtlRaiseException"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__RtlTimeFieldsToTime) { kernel::Unimplemented("RtlTimeFieldsToTime"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__RtlTimeToTimeFields) { kernel::Unimplemented("RtlTimeToTimeFields"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__RtlUnwind) { kernel::Unimplemented("RtlUnwind"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__XamGetExecutionId) { kernel::Unimplemented("XamGetExecutionId"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__XamVoiceClose) { kernel::Unimplemented("XamVoiceClose"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__XamVoiceCreate) { kernel::Unimplemented("XamVoiceCreate"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__XamVoiceHeadsetPresent) { kernel::Unimplemented("XamVoiceHeadsetPresent"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__XamVoiceSubmitPacket) { kernel::Unimplemented("XamVoiceSubmitPacket"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp____C_specific_handler) { kernel::Unimplemented("__C_specific_handler"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp___vsnprintf) { kernel::Unimplemented("_vsnprintf"); ctx.r3.u64 = 0; }
PPC_FUNC(__imp__sprintf) { kernel::Unimplemented("sprintf"); ctx.r3.u64 = 0; }
