#!/usr/bin/env python3
"""Writes runtime/gpu/vulkan/vulkan_functions.inc: every Vulkan entry point the
runtime calls, each under the dispatch level it has to be loaded from.

A build that loads Vulkan itself -- Android, where the driver may be one the
player imported rather than the system's (runtime/android/driver.cpp) -- has no
link-time symbols to call: every vkSomething is a function pointer, filled in
from vkGetInstanceProcAddr and then, for the ones a device dispatches,
vkGetDeviceProcAddr, which skips the loader's trampoline on every draw call.

Run it after adding a call to an entry point the runtime did not use before:

    python3 tools/gen_vulkan_loader.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = os.path.join(ROOT, "runtime", "gpu", "vulkan")
OUTPUT = os.path.join(SOURCES, "vulkan_functions.inc")

# Loaded with a null instance, before there is one.
GLOBAL = {
    "vkCreateInstance",
    "vkEnumerateInstanceExtensionProperties",
    "vkEnumerateInstanceLayerProperties",
    "vkEnumerateInstanceVersion",
}

# Dispatched on an instance or a physical device. Everything else that takes a
# device, a queue or a command buffer is loaded from the device.
INSTANCE = {
    "vkCreateDevice",
    "vkDestroyDevice",          # deliberately here: the device-level pointers
                                # are dropped when the device goes, and this
                                # one has to outlive them
    "vkDestroyInstance",
    "vkEnumerateDeviceExtensionProperties",
    "vkEnumeratePhysicalDevices",
    "vkGetDeviceProcAddr",
    "vkCreateAndroidSurfaceKHR",
    "vkDestroySurfaceKHR",
    "vkCreateDebugUtilsMessengerEXT",
    "vkDestroyDebugUtilsMessengerEXT",
}

# Entry points the platform layer needs that no other source file names.
EXTRA = {
    "vkCreateAndroidSurfaceKHR",
    "vkEnumerateInstanceExtensionProperties",
    "vkEnumerateInstanceVersion",
    "vkGetPhysicalDeviceSurfacePresentModesKHR",
    "vkGetPhysicalDeviceMemoryProperties",
}

# Guarded: they only exist when the header was compiled for that platform.
GUARDS = {
    "vkCreateAndroidSurfaceKHR": "VK_USE_PLATFORM_ANDROID_KHR",
}

# Names that look like entry points and are not.
NOT_FUNCTIONS = {"vkResult"}

# Loaded from the library itself rather than from a dispatchable object, and
# declared by hand in loader.h: it is what loads everything else.
BOOTSTRAP = {"vkGetInstanceProcAddr"}

CALL = re.compile(r"\b(vk[A-Z][A-Za-z0-9]*)\s*\(")


def found():
    names = set(EXTRA)
    for folder, _, files in os.walk(SOURCES):
        for name in sorted(files):
            if not name.endswith((".cpp", ".h")):
                continue
            with open(os.path.join(folder, name), encoding="utf-8") as source:
                for line in source:
                    # Declarations of our own function pointers, not calls.
                    if line.lstrip().startswith("//"):
                        continue
                    names.update(CALL.findall(line))
    return {name for name in names if name not in NOT_FUNCTIONS and name not in BOOTSTRAP}


def level(name):
    if name in GLOBAL:
        return "GLOBAL"
    if name in INSTANCE or name.startswith("vkGetPhysicalDevice"):
        return "INSTANCE"
    return "DEVICE"


def main():
    names = found()
    lines = [
        "// Generated by tools/gen_vulkan_loader.py -- do not edit by hand.",
        "//",
        "// Every Vulkan entry point the runtime calls, under the dispatch level it is",
        "// loaded from: MW2_VK_GLOBAL before there is an instance, MW2_VK_INSTANCE from",
        "// vkGetInstanceProcAddr, MW2_VK_DEVICE from vkGetDeviceProcAddr once the device",
        "// exists (and from the instance until then).",
        "",
    ]
    for want in ("GLOBAL", "INSTANCE", "DEVICE"):
        for name in sorted(names):
            if level(name) != want:
                continue
            guard = GUARDS.get(name)
            if guard:
                lines.append("#ifdef %s" % guard)
            lines.append("MW2_VK_%s(%s)" % (want, name))
            if guard:
                lines.append("#endif")
        lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write("\n".join(lines))
    print("%s: %d entry points" % (os.path.relpath(OUTPUT, ROOT), len(names)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
