#!/usr/bin/env python3
"""Generate logging stubs for every kernel/XAM import the runtime does not yet
implement. An import counts as implemented once some runtime/kernel/*.cpp file
defines PPC_FUNC(__imp__<name>)."""
import glob, os, re, sys
import title

ROOT = title.ROOT
need = [l.strip() for l in open(title.ppc("kernel_imports.txt")) if l.strip()]

implemented = set()
for f in glob.glob(os.path.join(ROOT, "runtime/kernel/*.cpp")):
    if f.endswith("stubs_generated.cpp"):
        continue
    implemented |= set(re.findall(r'PPC_FUNC\(__imp__([A-Za-z0-9_]+)\)', open(f).read()))

missing = sorted(set(need) - implemented)
out = title.ppc("stubs_generated.cpp")
with open(out, "w") as o:
    o.write("// Generated by tools/gen_kernel_stubs.py -- do not edit.\n")
    o.write("// Every import here logs once and returns 0, so a run reports exactly\n")
    o.write("// which ones the game actually reaches.\n")
    o.write('#include <ppc_recomp_shared.h>\n#include "kernel/kernel.h"\n\n')
    for n in missing:
        o.write(f'PPC_FUNC(__imp__{n}) {{ kernel::Unimplemented("{n}"); ctx.r3.u64 = 0; }}\n')

unknown = sorted(implemented - set(need))
print(f"kernel imports: {len(need)} needed, {len(implemented & set(need))} implemented, {len(missing)} stubbed")
if unknown:
    print(f"  note: implemented but not imported by the game: {unknown}")
